### ISSUE TITLE
Comments on code.R

### ISSUE THREAD

**Issue by batson** [constantAmateur/MCVR#1]
Line 55: "Unde-estimate"
Line 62: "performe"
line 141 could have a more descriptive error message :-)

For gene selection, you assume that variable genes will be used. This is a sensible default for the Seurat workflow. It might also be nice to have an easy way use everything.

I like quantifying the sampling error, and returning a range which will likely contain the true minimum. In the example, you suggest taking the first element of that list, which will be the smallest number of PCs. It makes more sense to me to return both the empirical min and the plausible range, so that the empirical min can be used downstream.

`nSEs` is in standard dev units. People think in percent confidence interval. It might be nice to have that as the input, which can be converted to nSEs using a `cdf`.

Love the warnings and suggestions around Titration. That will help people use this method in a safe way, and also inform them how close they are 

The Poisson loss should probably be restricted to cases when no normalisation is used, as it has to be applied to count data.  Dropping the negative values doesn't make sense to me, as those do represent very bad predictions, and should have an adverse contribution not a zero contribution. What we have done internally is replace the output with `max(out, 1e-6)`, which puts a penalty on predicting negative numbers when indeed a count is seen. (The choice of `1e-6` is arbitrary.)

**Comment by constantAmateur** [comment]
Thanks for the comments.  I have updated the code to incorporate these changes.  

I do struggle with knowing what the best thing to do with Poisson likelihood when a model predicts 0 (or less) and there are non-zero counts.  Obviously the distribution value of infinity is not helpful, but all other choices seems so arbitrary.  But I guess it is best to leave it to the user to select their preferred penalty for predicting zeros.

**Comment by batson** [comment]
We experimented with letting that be another parameter. If X_pca is the
result of pca denoising and scaling back to counts, then we take max(X_pca,
eps) for some positive epsilon. Then searching over epsilon is just another
parameter.

Note that larger eps is better when the true value was nonzero, but worse
when the true value was zero, so there is a real tradeoff.
